---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 783092515213684736-sqe7HAIhX6MwXstS5UAKUgl7xIbEy5u
:access_token_secret: Du3AVJMKeanB4LA3UJHpvlnnp8KjIETzAgidcgApeN4DA
